export const tourismSeedData = [
  {
    slug: 'sigiriya',
    name: 'Sigiriya Ancient Rock Fortress',
    nodeId: 'UNESCO-LK-0014 • Central Archaeological Precinct',
    category: 'Heritage & Archaeological',
    categoryIcon: 'landmark',
    province: 'Central Province',
    district: 'Matale District (A6 Corridor)',
    elevation: '349m ASL',
    gps: '7.9570° N, 80.7603° E',
    corridor: 'A6 Corridor (Inamaluwa - Sigiriya Link B423)',
    difficulty: 'steep',
    status: 'open',
    statusText: 'PUBLISHED / OPEN',
    statusSub: '',
    foreignTariff: 'USD 36 (Foreign)',
    localTariff: 'LKR 150 (Local Citizen)',
    saarcTariff: 'USD 18 (SAARC Regional)',
    operatingHours: '06:30 – 17:30 Daily (Ticket counter closes 17:00)',
    guideRequirement: 'SLTDA Certified Guide Optional / West Gate Post',
    smsSummary: 'Sigiriya open. Clear skies. Water gardens operating. Mirror wall accessible. 1,200 steps clear.',
    overview: 'The 5th-century cliff citadel of King Kashyapa. An engineering marvel featuring sheer vertical staircases, the monumental Lion\'s Paw Gate, mirror-glazed ramparts, and ancient cloud-maiden frescoes.',
    heroImage: 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1600&q=80',
    ecoRestricted: false,
    verifiedAgo: '2 hrs ago',
    verifiedDesk: 'SLTDA Field Desk',
    subHeading: 'MATALE DISTRICT • CENTRAL CULTURAL TRIANGLE • 165 KM NORTH-EAST OF COLOMBO',
    specs: [
      { label: 'FOREIGN TOURIST TARIFF', value: 'USD $36 / ~LKR 11,500', sub: 'Includes Archaeological Museum, Gardens & Summit ascent.' },
      { label: 'ASCENT WINDOWS', value: '06:30 – 17:30 Daily', sub: 'Ticket counter closes strictly at 17:00.' },
      { label: 'ASCENT RATING', value: '1,200 Steps (Moderate)', sub: 'Cantilevered iron stairs anchored to open cliff face.' },
      { label: 'OFFICIAL GUIDES', value: 'West Gate Post', sub: 'Hire exclusively verified SLTDA badge holders.' }
    ],
    dossier: {
      title: 'The Sky Fortress of Kashyapa: 5th-Century Hydraulic Sovereign',
      badge: 'FIELD DOSSIER • CULTURAL TRIANGLE',
      ref: 'Catalogue Ref #SIG-477AD',
      paragraphs: [
        'Rising 200 meters above surrounding scrub jungles, the monolithic magma plug of Sigiriya was selected in 477 AD by King Kashyapa as his fortified redoubt following a dynastic patricide.',
        'Beyond defensive bastions, Kashyapa\'s master builders installed complex hydraulic systems—subterranean terracotta conduits, limestone gravity conduits, and pressurized fountain nozzles—that remain operational over fifteen centuries later.'
      ],
      highlights: [
        { title: 'Hydraulic Gardens', desc: 'Symmetrical aquatic pleasure parks engineered with subterranean conduits.', icon: 'water' },
        { title: 'Mirror Wall Graffiti', desc: 'Polished brick plaster carrying poetic verses inscribed by 8th-century voyagers.', icon: 'pencil' },
        { title: 'Summit Throne Acropolis', desc: '3-acre terraced palace summit with 360-degree vistas over dry zone plains.', icon: 'mountain' }
      ],
      gallery: [
        { title: "The Lion's Paws", image: 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=400&q=80' },
        { title: 'Mirror Wall Corridor', image: 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=400&q=80' },
        { title: 'Terraced Summit Ruins', image: 'https://images.unsplash.com/photo-1578652520385-c05f6f264b3c?auto=format&fit=crop&w=400&q=80' },
        { title: 'Water Gardens at Dawn', image: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=400&q=80' }
      ]
    },
    siteRules: [
      {
        title: 'Strict Prohibitions & Immediate Legal Penalties',
        badge: 'ENFORCED BY POLICE DESK',
        variant: 'danger',
        rules: [
          { label: 'NO DRONES (UAV Ban):', desc: 'Operating aerial drones within 2km is strictly forbidden under Civil Aviation Act.' },
          { label: 'Zero Single-Use Plastics:', desc: 'Discarding plastic bottles or smoking is completely prohibited.' }
        ]
      },
      {
        title: 'Cultural Etiquette & Sacred Sanctuary Etiquette',
        badge: 'ANTIQUITIES DEPT DIRECTIVE',
        variant: 'green',
        rules: [
          { label: 'Fresco Gallery Photography:', desc: 'Photography of any kind is strictly prohibited inside the spiral Fresco Cave.' },
          { label: 'Mirror Wall Preservation:', desc: 'Touching or scratching the plaster of the Mirror Wall is a criminal offense.' }
        ]
      },
      {
        title: 'Wildlife Protocol: Giant Hornet & Macaque Advisory',
        badge: 'CAUTION ACTIVE',
        variant: 'caution',
        rules: [
          { label: 'Hornet Quiet Zones:', desc: 'Observe absolute silence in marked overhang areas beneath Vespa affinis nests.' },
          { label: 'Toque Macaque Monkeys:', desc: 'Wild primates grab open food and exposed camera straps. Keep bags sealed.' }
        ]
      }
    ],
    corridorRadar: [
      { route: 'A6 Highway (Colombo - Dambulla)', status: 'Clear', statusVariant: 'open', desc: 'Dual-carriageway sector fully passable.' },
      { route: 'Inamaluwa - Sigiriya Link (B423)', status: 'Clear', statusVariant: 'open', desc: 'Secondary asphalt corridor fully passable. Caution: wild elephants after dusk.' },
      { route: 'Habarana Junction Transit Hub', status: 'Normal', statusVariant: 'open', desc: 'Fuel stations operating at 100% capacity.' }
    ],
    campAndStay: [
      { name: 'Pidurangala Wilderness Camp', badge: 'VERIFIED SAFE', variant: 'open', desc: '1.4 km North. Forest tent decks facing northern rock wall.' },
      { name: 'Sigiriya Heritage Eco Village', badge: 'LOW GEN FUEL', variant: 'caution', desc: '2.2 km West. Main grid functional; backup generator on 30% diesel reserve.' },
      { name: 'Aliya Resort & Spa Node', badge: 'VERIFIED SAFE', variant: 'open', desc: 'High-capacity connectivity node with Starlink terminal.' }
    ],
    hotlines: [
      { label: 'Tourist Police (Sigiriya Post)', number: '066 228 6520', isPrimary: true },
      { label: '1990 Suwa Seriya Ambulance', number: '1990 (Free)', isPrimary: true, isEmergency: true },
      { label: 'Sri Lanka Tourism Hotline', number: '1912', isPrimary: false },
      { label: 'Dambulla Base Hospital', number: '066 228 4822', isPrimary: false }
    ],
    regulations: {
      plastics: true,
      drones: true,
      frescoes: true,
      hornets: true,
      attire: true,
      macaques: true
    },
    contacts: {
      touristPolice: '+94 66 228 6520',
      hospital: 'Dambulla Base Hospital (14km)',
      ambulance: '1990 Suwa Seriya (Free Dispatch)'
    }
  },
  {
    slug: 'ella-rock',
    name: 'Ella Rock & Ravana Ridge',
    nodeId: 'NAT-UVA-8821 • Railway Trackhead Escarpment',
    category: 'Nature & Hiking',
    categoryIcon: 'trees',
    province: 'Uva Province',
    district: 'Badulla District (Ella Gap)',
    elevation: '1,320m ASL',
    gps: '6.8520° N, 81.0460° E',
    corridor: 'Main Line Rail Sector / Ella Gap',
    difficulty: 'moderate',
    status: 'caution',
    statusText: 'CAUTION: MIST WARNING',
    statusSub: '',
    foreignTariff: 'Free Trail Access',
    localTariff: 'Licensed Guide Optional',
    saarcTariff: 'Free',
    operatingHours: 'Daylight hours: 06:00 – 17:00',
    guideRequirement: 'Licensed Guide Optional',
    smsSummary: 'Heavy mist past Kithalella siding. Footpath wet. Escarpment visibility 15m. Guide advised.',
    overview: 'Prominent cliff outcrop overlooking Ella Gap and Little Adam\'s Peak. Trail follows active railway track from Ella station before ascending through eucalyptus plantations.',
    heroImage: 'https://images.unsplash.com/photo-1546708973-b339540b5162?auto=format&fit=crop&w=1600&q=80',
    ecoRestricted: false,
    verifiedAgo: 'Yesterday 18:30',
    verifiedDesk: 'Ella Tour Police Node'
  },
  {
    slug: 'little-adams-peak',
    name: "Little Adam's Peak & Nine Arches",
    nodeId: 'PAN-UVA-1090 • Demodara Viaduct Sector',
    category: 'Viewpoints & Walking',
    categoryIcon: 'mountain',
    province: 'Uva Province',
    district: 'Badulla District',
    elevation: '1,141m ASL',
    gps: '6.8640° N, 81.0580° E',
    corridor: 'Demodara Viaduct Link',
    difficulty: 'easy',
    status: 'open',
    statusText: 'PUBLISHED / OPEN',
    statusSub: '',
    foreignTariff: 'Free Walkway',
    localTariff: 'Flying Ravana Zipline Paid',
    saarcTariff: 'Free',
    operatingHours: 'Open 24/7 (Optimal sunrise/sunset)',
    guideRequirement: 'No guide needed',
    smsSummary: 'Clear visibility across Demodara valley. Nine Arches train transit on schedule.',
    overview: 'Gentle pyramid-shaped peak surrounded by tea estates, offering panoramic viewpoints of Ella Rock and the iconic colonial Nine Arches stone viaduct bridge.',
    heroImage: 'https://images.unsplash.com/photo-1578652520385-c05f6f264b3c?auto=format&fit=crop&w=1600&q=80',
    ecoRestricted: false,
    verifiedAgo: '3 days ago',
    verifiedDesk: 'Highland Ranger Stn'
  },
  {
    slug: 'horton-plains',
    name: "Horton Plains & World's End",
    nodeId: 'DWC-CP-4402 • Ohiya Plateau Entrance',
    category: 'National Park & Cloud Forest',
    categoryIcon: 'cloud-sun',
    province: 'Central Province',
    district: 'Nuwara Eliya (B312 Access)',
    elevation: '2,135m ASL',
    gps: '6.8028° N, 80.8092° E',
    corridor: 'Pattipola – Ohiya Pass',
    difficulty: 'moderate',
    status: 'open',
    statusText: 'PUBLISHED / OPEN',
    statusSub: 'Zero Single-Use Plastics',
    foreignTariff: 'USD 35 + VAT',
    localTariff: 'DWC Group Vehicle Permit',
    saarcTariff: 'USD 20',
    operatingHours: '06:00 – 16:00 (Entry closes 14:00)',
    guideRequirement: 'Ranger guide available at visitor centre',
    smsSummary: 'World\'s End clear until 09:30. Baker\'s Falls trail open. Zero polythene check strictly enforced.',
    overview: 'Protected cloud forest plateau harboring endemic flora and the staggering 870m vertical precipice known as World\'s End.',
    heroImage: 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?auto=format&fit=crop&w=1600&q=80',
    ecoRestricted: true,
    verifiedAgo: '5 hrs ago',
    verifiedDesk: 'Dept of Wildlife Ward'
  },
  {
    slug: 'dunhinda-falls',
    name: 'Dunhinda Falls Gorge',
    nodeId: 'GEO-UVA-6299 • Badulu Oya Pathway',
    category: 'Waterfalls & Gorges',
    categoryIcon: 'droplets',
    province: 'Uva Province',
    district: 'Badulla Urban Council',
    elevation: '670m ASL',
    gps: '6.9856° N, 81.0664° E',
    corridor: 'Badulla – Mahiyanganaya Road',
    difficulty: 'moderate',
    status: 'draft',
    statusText: 'DRAFT / RANGER REVIEW',
    statusSub: '',
    foreignTariff: 'LKR 300 (Local)',
    localTariff: 'Foreign Tariff Pending',
    saarcTariff: 'LKR 300',
    operatingHours: '07:00 – 17:00 Daily',
    guideRequirement: 'Local pathway guide optional',
    smsSummary: 'Waterfall volume normal. Pathway damp; footbridge repairs ongoing near Lower Cascade.',
    overview: 'One of Sri Lanka\'s most renowned cascades plunging 64 meters into a churning limestone gorge along the Badulu Oya.',
    heroImage: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?auto=format&fit=crop&w=1600&q=80',
    ecoRestricted: false,
    verifiedAgo: 'Just now',
    verifiedDesk: 'Silva (Admin Draft)'
  },
  {
    slug: 'pigeon-island',
    name: 'Pigeon Island Marine National Park',
    nodeId: 'MAR-EP-7741 • Nilaveli Boat Station',
    category: 'Coastal & Marine',
    categoryIcon: 'waves',
    province: 'Eastern Province',
    district: 'Trincomalee Coast',
    elevation: 'Sea Level (0m)',
    gps: '8.7206° N, 81.2067° E',
    corridor: 'Nilaveli Coastal Marine Hub',
    difficulty: 'easy',
    status: 'danger',
    statusText: 'SUSPENDED',
    statusSub: 'High Monsoonal Swell',
    foreignTariff: 'USD 25 (Marine Pass)',
    localTariff: 'Boat Charter Separate',
    saarcTariff: 'USD 15',
    operatingHours: 'Temporarily closed during swell',
    guideRequirement: 'Licensed boat operator mandatory',
    smsSummary: 'Marine access closed by Trinco Harbour Master. Swell > 2.5m. Boat launches suspended.',
    overview: 'Pristine offshore coral reef sanctuary renowned for blacktip reef sharks, green sea turtles, and colorful marine bio-diversity.',
    heroImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80',
    ecoRestricted: false,
    verifiedAgo: '1 hr ago',
    verifiedDesk: 'Trinco Harbour Master'
  }
];

export const campsiteSeedData = [
  {
    slug: 'knuckles-01',
    name: 'Knuckles High Ridge Campsite #03',
    classification: 'Official DWC National Park Camp',
    location: 'Meemure / Knuckles Range (Matale)',
    province: 'Central Province',
    district: 'Matale District',
    terrainBelt: 'Central Highlands',
    elevation: '1,420m',
    gps: '7.4628° N, 80.7915° E',
    rangerStation: 'Hunnasgiriya Range Office / 14km foot trail via Deanston',
    difficulty: 'extreme',
    featureBadge: 'Perennial Stream OK',
    featureBadgeType: 'green',
    pitchesCount: 4,
    pitchesLabel: '4 Pitches',
    maxCampers: 16,
    campersLabel: 'Max 16 Campers',
    footprint: '2-man & 4-man footprint',
    tariffLkr: 'LKR 2,500',
    tariffUnit: 'pitch',
    tariffExtra: '+ DWC Wildlife Entry',
    tariffUsd: '$25.00',
    rangerTariff: 'Rs. 3,500 / day (DWC Field Guide)',
    season: 'Jan – Apr & Jul – Sep',
    duration: 'Max 2 consecutive nights',
    status: 'open',
    statusText: 'OPEN • SPRING RUNNING',
    statusSub: 'No flash-flood warning',
    clearanceOffice: 'Forest Dept Range Office',
    clearanceSub: 'Hunnasgiriya Sub-Post',
    lastSynced: '15 mins ago',
    lastSyncedChannel: 'via Matale VHF',
    hasWaterSpring: true,
    requiresRanger: false,
    maxGroup12: true,
    subtitle: 'MEEMURE SIDE ELEVATION: 1,480M • MATALE DISTRICT – CENTRAL HIGHLANDS BIOSPHERE RESERVE',
    tagline: 'Perched at 1,480 meters on the watershed ridge connecting Deanston and Meemure, High Ridge Pitch 02 is one of the island\'s most secluded wilderness camping sanctuaries.',
    trailApproach: 'The trail commences from Deanston Conservation Centre (11km total route), winding through dense montane pygmy forests enveloped in moss and sheer granite escarpments.',
    temperature: '16°C (Mist)',
    image: 'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=1600&q=80',
    badges: [
      { label: 'DWC Official Wilderness Campsite', variant: 'green' },
      { label: 'Current Status: Open - Spring Flowing', variant: 'green-pulse' },
      { label: 'Trail Grade: Extreme Ridge Hike (4.5 hrs)', variant: 'amber-trail' }
    ],
    specs: [
      { label: 'PITCH CAPACITY', value: '4 Cleared Pads', sub: 'Strict limit of 16 campers / 24 hrs' },
      { label: 'TARIFF / NIGHT', value: 'USD $25 Foreign', sub: 'SAARC 50% • Local LKR 2,500 + DWC entry' },
      { label: 'OPTIMAL SEASON', value: 'Jan – Apr & Jul – Sep', sub: 'Oct-Dec: Heavy rains & flash floods' },
      { label: 'POTABLE WATER', value: 'Perennial Spring', sub: '80m West; boil or tablet treat' },
      { label: 'SANITATION', value: 'Bio-Compost Pit', sub: 'Timber latrine with sawdust box' }
    ],
    gearChecklist: [
      { title: 'Heavy-Duty Leech Socks', desc: 'Tight-weave knee-high barriers with tobacco leaf or salt tincture rub.' },
      { title: '3-Season Waterproof Tent', desc: 'Hydrostatic head minimum 5,000mm with reinforced guy-lines.' },
      { title: '45L Roll-Top Dry Sack', desc: 'Monsoonal cloud bursts saturate pack covers; keep sleeping bag dry.' },
      { title: 'Sub-Zero Thermal Layer & Headlamp', desc: 'Night temperatures plummet to 10°C in dense mist.' }
    ],
    rulesQuadrants: [
      {
        id: '01',
        title: 'Quadrant 01',
        subtitle: 'General Rules & Camper Conduct',
        badge: 'Conduct & Timing',
        items: [
          { label: 'Check-in daylight hours strictly before 17:30 IST', desc: 'No trekking permitted along sheer escarpment edges after dark.' },
          { label: 'Maximum continuous stay: 2 consecutive nights', desc: 'Per permit to safeguard fragile cloud-forest topsoil.' },
          { label: 'Quiet wilderness hours: 20:00 to 06:00', desc: 'Acoustic speakers and portable generators are forbidden.' }
        ],
        footnote: 'Violation fine: LKR 10,000 / immediate revocation of permit.'
      },
      {
        id: '02',
        title: 'Quadrant 02',
        subtitle: 'Environmental Protection & Zero Waste',
        badge: 'Leave-No-Trace',
        items: [
          { label: 'Absolute Zero-Polythene Zone', desc: 'Single-use shopping bags confiscated at Deanston Checkpoint.' },
          { label: 'Pack-It-In, Pack-It-Out', desc: 'All dehydrated food packaging and trash must be carried back.' },
          { label: 'Water Source Hygiene', desc: 'No synthetic soaps or chemicals within 50m of natural stream conduits.' }
        ],
        footnote: 'Checked against ranger dispatch register upon exit.'
      },
      {
        id: '03',
        title: 'Quadrant 03',
        subtitle: 'Fire Restrictions & Open Hearth Safety',
        badge: 'CRITICAL RISK / RED',
        variant: 'danger',
        items: [
          { label: 'High Wildfire Risk: Ground campfires prohibited', desc: 'Subject to immediate detention under Fauna & Flora Protection Ordinance.' },
          { label: 'Permitted Cooking: Designated stone hearth ONLY', desc: 'Supervised by assigned beat tracker.' }
        ],
        footnote: 'Forest Department patrols conduct drone thermal surveillance nightly.'
      },
      {
        id: '04',
        title: 'Quadrant 04',
        subtitle: 'Wildlife Precautions & Ridge Hazards',
        badge: 'Wild Fauna & Weather',
        variant: 'caution',
        items: [
          { label: 'Leech & Viper Advisory: Land leeches present', desc: 'Inspect boots carefully for venomous hump-nosed pit vipers.' },
          { label: 'Elephant Corridor Alert: Pitch on leveled platforms', desc: 'Do not pitch tents across active game tracks.' }
        ],
        footnote: 'Emergency evacuation whistle frequency: 3 short blasts repeated at 1-min intervals.'
      }
    ],
    rangerOffice: {
      hotline: '+94 66 222 4110',
      hotlineSub: 'Hunnasgiriya Range Headquarters (24/7 Desk)',
      channel: 'Channel 88 (146.520 MHz)',
      channelCallsign: "Callsign: 'Dumbara Cloud Guard Beta'",
      rescueSiding: 'Deanston Beat Office',
      rescueSub: 'Satellite link active (Iridium PTT Relay)'
    },
    corridorAccess: [
      {
        route: 'Corridor: Hasalaka – Meemure Route',
        timeAgo: '14m ago',
        title: 'Hasalaka-Meemure Tractor Pass',
        desc: 'Impassable to private 2WD & 4WD cars. Heavy boulder run-off near Pitawala. Only heavy tractors operational.',
        activeFrom: 'Relay active from Hunnasgiriya',
        source: 'Divisional Secretariat Log',
        status: 'caution'
      },
      {
        route: 'Deanston Main Forest Track',
        timeAgo: '1 hr ago',
        title: 'Passage Open to Permitted Hikers',
        desc: 'Foot trail clear of mudslides up to Mini World\'s End junction.',
        activeFrom: '',
        source: '',
        status: 'open'
      }
    ],
    nearbySpots: [
      { name: "Corbet's Gap Staging", badge: 'High Wind Caution', badgeType: 'caution', distance: '3.6 km North-West • Elevation 1,220m', desc: 'Spectacular wind tunnel gap between Knuckles and Dumbanagala peaks.' },
      { name: 'Nitro Caves Bivouac', badge: 'DWC Permit Only', badgeType: 'badge-dark', distance: '5.2 km South-East • Cavern Pitch', desc: 'Natural saltpeter cavern inhabited by thousands of bats.' },
      { name: 'Pitawala Pathana Escarpment', badge: 'Open Daylight', badgeType: 'open', distance: '8.4 km North • Grassland Plateau', desc: 'Unique montane grassland with endemic frog pools and 300m drop.' }
    ],
    facilities: { spring: true, latrine: true, ring: true, foodCache: true, solar: false, noGenerators: true },
    contacts: { hotline: '+94 66 222 4110', vhfChannel: 'Channel 88 (146.520 MHz)', medicalCenter: 'Teldeniya Base (38km)' },
    smsSummary: 'Plot 02 open. Knuckles ridge cleared. Water spring running. Ranger check-in at Deanston'
  },
  {
    slug: 'horton-plains-01',
    name: 'Horton Plains Campsite 01 (Chimney Pool)',
    classification: 'Official DWC National Park Camp',
    location: 'Horton Plains Plateau (Nuwara Eliya)',
    province: 'Central Province',
    district: 'Nuwara Eliya District',
    terrainBelt: 'Central Highlands',
    elevation: '2,135m',
    gps: '6.8050° N, 80.8120° E',
    rangerStation: 'Pattipola Ranger Gate',
    difficulty: 'moderate',
    featureBadge: 'Sub-zero Frost',
    featureBadgeType: 'blue',
    pitchesCount: 3,
    pitchesLabel: '3 Pitches',
    maxCampers: 12,
    campersLabel: 'Max 12 Campers',
    footprint: 'High-wind stakes required',
    tariffLkr: 'USD 25 Foreign',
    tariffUnit: '',
    tariffExtra: 'LKR 1,500 (Local Resident)',
    tariffUsd: '$25.00',
    rangerTariff: 'DWC Warden Escort Included',
    season: 'Year-round (Best Jan - Mar)',
    duration: '1 night max',
    status: 'caution',
    statusText: 'OPEN • FROST / SUB-ZERO NIGHT CAUTION',
    statusSub: 'Zero degree thermal kit mandatory',
    clearanceOffice: 'Mandatory Online DWC',
    clearanceSub: 'Pattipola & Ohiya Gate Pass',
    lastSynced: '2 hrs ago',
    lastSyncedChannel: 'DWC Nuwara Eliya Web',
    hasWaterSpring: true,
    requiresRanger: false,
    maxGroup12: true
  },
  {
    slug: 'corbets-gap',
    name: "Corbet's Gap Wind Staging Pitch",
    classification: 'Community Managed Wilderness',
    location: "Rangala - Corbet's Saddle (Kandy)",
    province: 'Central Province',
    district: 'Kandy District',
    terrainBelt: 'Central Highlands',
    elevation: '1,220m',
    gps: '7.3650° N, 80.7850° E',
    rangerStation: 'Rangala Police Post',
    difficulty: 'moderate',
    featureBadge: '60km/h Gusts',
    featureBadgeType: 'alert',
    pitchesCount: 2,
    pitchesLabel: '2 Pitches',
    maxCampers: 8,
    campersLabel: 'Max 8 Campers',
    footprint: 'Exposed ridge line',
    tariffLkr: 'Free Community Pitch',
    tariffUnit: '',
    tariffExtra: 'Community Stewardship',
    tariffUsd: 'Free',
    rangerTariff: 'Community Guide Optional',
    season: 'Mar – May & Sep – Oct',
    duration: '1 night',
    status: 'danger',
    statusText: 'TEMPORARILY CLOSED: 60KM/H GALES',
    statusSub: 'Gale advisory in effect',
    clearanceOffice: 'Local Police Station Register',
    clearanceSub: 'Rangala Police Post Log',
    lastSynced: '35 mins ago',
    lastSyncedChannel: 'Disaster Mgmt Centre (Kandy)',
    hasWaterSpring: false,
    requiresRanger: false,
    maxGroup12: false
  },
  {
    slug: 'gala-muduna',
    name: 'Gala Muduna Cloud Forest Camp',
    classification: 'Forest Department Eco-Reserve',
    location: 'Hasalaka Ridge (Central Range)',
    province: 'Central Province',
    district: 'Matale District',
    terrainBelt: 'Knuckles Foothills',
    elevation: '980m',
    gps: '7.4120° N, 80.8950° E',
    rangerStation: 'Hasalaka Forest Beat Office',
    difficulty: 'moderate',
    featureBadge: 'Ranger Required',
    featureBadgeType: 'amber',
    pitchesCount: 5,
    pitchesLabel: '5 Pitches',
    maxCampers: 20,
    campersLabel: 'Max 20 Campers',
    footprint: 'Forest edge clearing',
    tariffLkr: 'LKR 3,000',
    tariffUnit: 'tent',
    tariffExtra: '+ Certified Guide Fee',
    tariffUsd: '$20.00',
    rangerTariff: 'Rs. 2,500 / day',
    season: 'Jan – Sep',
    duration: '2 nights max',
    status: 'caution',
    statusText: 'OPEN • RANGER ESCORT MANDATORY',
    statusSub: 'Elephant corridor boundary',
    clearanceOffice: 'Forest Dept Hasalaka',
    clearanceSub: 'Beat Office Registration',
    lastSynced: 'Yesterday',
    lastSyncedChannel: 'Hasalaka Beat Officer Log',
    hasWaterSpring: true,
    requiresRanger: true,
    maxGroup12: true
  },
  {
    slug: 'ella-peak',
    name: 'Ella Peak Wilderness Bivouac',
    classification: 'Forest Department Eco-Reserve',
    location: 'Ella Forest Reserve (Badulla)',
    province: 'Uva Province',
    district: 'Badulla District',
    terrainBelt: 'Uva Passages',
    elevation: '1,340m',
    gps: '6.8480° N, 81.0420° E',
    rangerStation: 'Badulla Divisional Secretariat',
    difficulty: 'moderate',
    featureBadge: 'Field Inspection Pending',
    featureBadgeType: 'draft',
    pitchesCount: 6,
    pitchesLabel: '6 Pitches',
    maxCampers: 24,
    campersLabel: 'Max 24 Campers',
    footprint: 'Staging for Ella Rock trail',
    tariffLkr: 'LKR 1,500',
    tariffUnit: 'pitch',
    tariffExtra: 'Proposed Municipal Fee',
    tariffUsd: '$10.00',
    rangerTariff: 'Self-guided',
    season: 'Year-round',
    duration: '2 nights max',
    status: 'draft',
    statusText: 'DRAFT / PENDING FOREST OFFICER AUDIT',
    statusSub: 'Awaiting soil stability certificate',
    clearanceOffice: 'Badulla Divisional Secretariat',
    clearanceSub: 'Environmental Division',
    lastSynced: '4 days ago',
    lastSyncedChannel: 'Field Dossier v2',
    hasWaterSpring: false,
    requiresRanger: false,
    maxGroup12: true
  }
];

export const townSeedData = [
  { name: 'Kandy', slug: 'kandy', district: 'Kandy', province: 'Central Province', belt: 'hill_country', lat: 7.2906, lng: 80.6337 },
  { name: 'Ella', slug: 'ella', district: 'Badulla', province: 'Uva Province', belt: 'hill_country', lat: 6.8667, lng: 81.0466 },
  { name: 'Nuwara Eliya', slug: 'nuwara-eliya', district: 'Nuwara Eliya', province: 'Central Province', belt: 'hill_country', lat: 6.9497, lng: 80.7891 },
  { name: 'Sigiriya', slug: 'sigiriya', district: 'Matale', province: 'Central Province', belt: 'cultural_triangle', lat: 7.9570, lng: 80.7603 },
  { name: 'Trincomalee', slug: 'trincomalee', district: 'Trincomalee', province: 'Eastern Province', belt: 'east_coast', lat: 8.5874, lng: 81.2152 }
];
export const townsData = [
  {
    id: 'ella',
    slug: 'ella',
    name: 'Ella',
    corridor: 'Ella Valley & Wellawaya Passages',
    district: 'Badulla',
    province: 'Uva'
  },
  {
    id: 'haputale',
    slug: 'haputale',
    name: 'Haputale',
    corridor: 'Haputale Heights & Beragala Pass',
    district: 'Badulla',
    province: 'Uva'
  },
  {
    id: 'nuwara-eliya',
    slug: 'nuwara-eliya',
    name: 'Nuwara Eliya',
    corridor: 'A5 Ramboda Pass & Hakgala Valley',
    district: 'Nuwara Eliya',
    province: 'Central'
  },
  {
    id: 'hatton',
    slug: 'hatton',
    name: 'Hatton & Peak',
    corridor: "Adam's Peak · Nallathanniya Base",
    district: 'Nuwara Eliya',
    province: 'Central'
  },
  {
    id: 'meemure',
    slug: 'meemure',
    name: 'Meemure',
    corridor: 'Knuckles Range · Heen Ganga Basin',
    district: 'Kandy',
    province: 'Central'
  },
  {
    id: 'arugam-bay',
    slug: 'arugam-bay',
    name: 'Arugam Bay',
    corridor: 'East Coast · Panama Corridor',
    district: 'Ampara',
    province: 'Eastern'
  },
  {
    id: 'galle',
    slug: 'galle',
    name: 'Galle Coast',
    corridor: 'Southern Coastal Belt · Galle Fort',
    district: 'Galle',
    province: 'Southern'
  },
  {
    id: 'mirissa',
    slug: 'mirissa',
    name: 'Mirissa',
    corridor: 'Mirissa Bay & Weligama Pass',
    district: 'Matara',
    province: 'Southern'
  }
];

export const noticesData = [
  {
    id: 'notice-zion-view',
    customId: 'notice-zion-view',
    title: 'Zion View',
    town: 'ella',
    townName: 'Ella',
    corridor: 'Ella Valley · A23 Corridor',
    issue: 'road_closed',
    status: 'disrupted',
    isUrgent: true,
    headline: 'Road closed · Wellawaya-Ella passage',
    description: 'Culvert repair at 14th Mile Post. Light 4x4 and three-wheelers can divert via Bandarawela-Poonagala road. Stays running generator 6pm-10pm.',
    bypassAdvice: '4x4 pickup shuttle active from Bandarawela rail depot for verified guests. Avoid heavy vans on Poonagala bypass.',
    utilities: {
      generatorStatus: '6:00 PM - 10:00 PM Active',
      waterStatus: 'Gravity Feed 3000L Reserve',
      connectivityStatus: 'Dialog 4G + Starlink Relay Active'
    },
    contactNumber: '077 412 8901',
    verifiedBy: 'Estate Dispatch',
    verifiedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-nine-skies-rest',
    customId: 'notice-nine-skies-rest',
    title: 'Nine Skies Rest',
    town: 'ella',
    townName: 'Ella',
    corridor: 'Ella Pass · B360 Passara Pass',
    issue: 'landslide',
    status: 'disrupted',
    isUrgent: true,
    headline: 'Passara road earth slip',
    description: 'Small slip blocking heavy vans near bridge 4. Local RDA JCB crew on site clearing boulders. Expect 3-4 hr delay. Walking luggage transfer operational.',
    bypassAdvice: 'Pedestrian bypass bridge open for backpack transfers. Local porter team stationed at Demodara loop.',
    utilities: {
      generatorStatus: 'Full Day Diesel Generator',
      waterStatus: 'Normal Gravity Supply',
      connectivityStatus: 'Mobitel 4G Active'
    },
    contactNumber: '077 391 2284',
    verifiedBy: 'Grama Niladhari',
    verifiedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 22 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-mandira-cottage',
    customId: 'notice-mandira-cottage',
    title: 'Mandira Cottage',
    town: 'haputale',
    townName: 'Haputale',
    corridor: 'Haputale Heights · Dambatenna Road',
    issue: 'no_water',
    status: 'caution',
    isUrgent: false,
    headline: 'Water supply cut until 4pm',
    description: 'Municipal pipeline rupture. No tap water supply until 4:00 PM. Backup water bowser en route, delayed by mist on the pass. 2000L backup tanks active, drinking water bottles distributed to all rooms.',
    bypassAdvice: 'Beragala-Haputale main road open to all vehicles. Drive with fog lamps.',
    utilities: {
      generatorStatus: 'Grid Power Stable',
      waterStatus: '2000L Backup Tank + Bottled Water',
      connectivityStatus: 'SLT Fibre Active'
    },
    contactNumber: '071 829 4432',
    verifiedBy: 'Water Board Notice',
    verifiedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-heritance-view-lodge',
    customId: 'notice-heritance-view-lodge',
    title: 'Heritance View Lodge',
    town: 'nuwara-eliya',
    townName: 'Nuwara Eliya',
    corridor: 'Highlands · A5 Ramboda Pass',
    issue: 'flooded_access',
    status: 'caution',
    isUrgent: false,
    headline: 'Extreme mist & < 5m visibility',
    description: 'Heavy mountain fog descending over Ramboda hairpin bends. Speed limit 15km/h advised. Water heaters running on dedicated generator circuit. Vehicles advised to drive in convoys with fog hazard indicators.',
    bypassAdvice: 'Drive via Gampola during daylight hours if unfamiliar with hairpin descent.',
    utilities: {
      generatorStatus: 'Dedicated Heater Generator Active',
      waterStatus: 'Normal Hot Water Available',
      connectivityStatus: 'Dialog 4G Active'
    },
    contactNumber: '052 222 3490',
    verifiedBy: 'Police Checkpoint',
    verifiedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-surf-nest',
    customId: 'notice-surf-nest',
    title: 'Surf Nest',
    town: 'arugam-bay',
    townName: 'Arugam Bay',
    corridor: 'East Coast · Panama Corridor',
    issue: 'road_closed',
    status: 'open',
    isUrgent: false,
    headline: 'Access clear · Panama road open',
    description: 'Monsoon swell manageable, grid power stable today. Tuk-tuks running standard coastal rates to Pottuvil without delays. Generators fueled, Starlink relay operational.',
    bypassAdvice: 'Main coastal corridor clear to all vehicular traffic.',
    utilities: {
      generatorStatus: 'Solar + Standby Genset',
      waterStatus: 'Well Water Filtered',
      connectivityStatus: 'Starlink 180Mbps Active'
    },
    contactNumber: '076 550 1198',
    verifiedBy: 'Coastguard Station',
    verifiedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-peak-trail-homestay',
    customId: 'notice-peak-trail-homestay',
    title: 'Peak Trail Homestay',
    town: 'hatton',
    townName: 'Hatton',
    corridor: "Adam's Peak · Nallathanniya Base",
    issue: 'bridge_unsafe',
    status: 'open',
    isUrgent: false,
    headline: 'Pilgrim trail & rail clear',
    description: 'Trains from Kandy running on schedule through Hatton station. Clear path from station, hot showers available, trail lights operating smoothly.',
    bypassAdvice: 'Hatton to Nallathanniya direct bus running every 30 minutes.',
    utilities: {
      generatorStatus: 'Solar Hot Water + CEB Stable',
      waterStatus: 'Continuous Mountain Stream',
      connectivityStatus: 'Dialog 4G Stable'
    },
    contactNumber: '071 559 8812',
    verifiedBy: 'Station Master',
    verifiedAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 130 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 65 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-knuckles-wilderness-nest',
    customId: 'notice-knuckles-wilderness-nest',
    title: 'Knuckles Wilderness Nest',
    town: 'meemure',
    townName: 'Meemure',
    corridor: 'Knuckles Range · Heen Ganga Basin',
    issue: 'flooded_access',
    status: 'caution',
    isUrgent: false,
    headline: 'Heen Ganga water level high',
    description: 'Normal vans cannot ford river crossing today. Homestay tractor stationed at Hunnasgiriya to ferry arriving guests across safely.',
    bypassAdvice: 'Call ahead at least 2 hours before reaching Hunnasgiriya junction for tractor transfer link.',
    utilities: {
      generatorStatus: 'Micro-Hydro + Battery Bank',
      waterStatus: 'Pure Spring Water System',
      connectivityStatus: 'Satellite Phone & Mesh Node'
    },
    contactNumber: '081 240 1902',
    verifiedBy: 'Local Guide Union',
    verifiedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-lagoon-gate-eco-hut',
    customId: 'notice-lagoon-gate-eco-hut',
    title: 'Lagoon Gate Eco Hut',
    town: 'arugam-bay',
    townName: 'Arugam Bay',
    corridor: 'Panama Sanctuary · Southern Spit',
    issue: 'flooded_access',
    status: 'disrupted',
    isUrgent: false,
    headline: 'Lagoon overflow on feeder road',
    description: 'Tide water over 200m track near salt marsh. Boat shuttle running continuously from Panama bridge for guests carrying rucksacks.',
    bypassAdvice: 'Park vehicle at Panama bridge compound. Free boat transfer for guests.',
    utilities: {
      generatorStatus: '100% Off-grid Solar Array',
      waterStatus: 'Rainwater Harvest Reserve',
      connectivityStatus: 'Dialog 3G Intermittent'
    },
    contactNumber: '063 224 8190',
    verifiedBy: 'Wildlife Warden',
    verifiedAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 180 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-rampart-street-villa',
    customId: 'notice-rampart-street-villa',
    title: 'Rampart Street Villa',
    town: 'galle',
    townName: 'Galle',
    corridor: 'Southern Coastal Belt · Galle Fort',
    issue: 'power_cut',
    status: 'open',
    isUrgent: false,
    headline: 'Expressway & town clear',
    description: 'Southern Expressway normal traffic, calm sea breeze, municipal CEB power grid completely stable without scheduled rolling outages.',
    bypassAdvice: 'Direct access via Pinnaduwa interchange.',
    utilities: {
      generatorStatus: 'Full Inverter Backup',
      waterStatus: 'City Main Constant Pressure',
      connectivityStatus: 'High-Speed Fibre 200Mbps'
    },
    contactNumber: '091 223 4488',
    verifiedBy: 'Tourist Police Desk',
    verifiedAt: new Date(Date.now() - 185 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 250 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 185 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-ella-mount-heaven',
    customId: 'notice-ella-mount-heaven',
    title: 'Ella Mount Heaven',
    town: 'ella',
    townName: 'Ella',
    corridor: 'Ella Valley · Passara Link',
    issue: 'road_closed',
    status: 'open',
    isUrgent: false,
    headline: 'Direct access via Bandarawela clear',
    description: 'Main Bandarawela road fully open. High-speed fiber WiFi running and hot water boilers operational for all checked-in travellers. Open stays nearby to accommodate diverted guests.',
    bypassAdvice: 'Use Bandarawela-Ella bypass road. No obstacles reported.',
    utilities: {
      generatorStatus: 'Auto-Start Generator',
      waterStatus: 'Full Spring Reservoirs',
      connectivityStatus: 'Fibre & 5G Available'
    },
    contactNumber: '077 654 3210',
    verifiedBy: 'Host Dispatch',
    verifiedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-tea-garden-rest',
    customId: 'notice-tea-garden-rest',
    title: 'Tea Garden Rest',
    town: 'haputale',
    townName: 'Haputale',
    corridor: 'Haputale · Beragala Pass',
    issue: 'no_water',
    status: 'open',
    isUrgent: false,
    headline: 'Mountain spring feed running',
    description: 'Private spring gravity tank full and operational. Solar backup inverter operational. Clear passage on Beragala ascent with normal driving conditions.',
    bypassAdvice: 'Beragala road fully clear.',
    utilities: {
      generatorStatus: 'Solar Inverter 24/7',
      waterStatus: 'Spring Water Operational',
      connectivityStatus: 'Mobitel 4G High Signal'
    },
    contactNumber: '071 998 7766',
    verifiedBy: 'Verified Host',
    verifiedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-misty-valley-inn',
    customId: 'notice-misty-valley-inn',
    title: 'Misty Valley Inn',
    town: 'nuwara-eliya',
    townName: 'Nuwara Eliya',
    corridor: 'Nuwara Eliya · Hakgala Route',
    issue: 'power_cut',
    status: 'resolved',
    isUrgent: false,
    headline: 'CEB power restored to Hakgala circuit',
    description: 'High winds caused transformer trip at 06:00, resolved by CEB emergency unit at 10:15. Heating and power fully back online across the estate.',
    bypassAdvice: 'All roads clear and fully passable.',
    utilities: {
      generatorStatus: 'Grid Restored + Standby Generator',
      waterStatus: 'Boilers Fully Active',
      connectivityStatus: 'Fibre + 4G Restored'
    },
    contactNumber: '052 887 6543',
    verifiedBy: 'CEB Emergency Desk',
    verifiedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString()
  },
  {
    id: 'notice-passara-ridge-haven',
    customId: 'notice-passara-ridge-haven',
    title: 'Passara Ridge Haven',
    town: 'ella',
    townName: 'Ella',
    corridor: 'Ella · Passara Ridge',
    issue: 'relocation',
    status: 'closed',
    isUrgent: false,
    headline: 'Temporary closure for retaining wall work',
    description: 'Scheduled geotechnical reinforcement at lower driveway. All current reservations safely relocated to partner lodge in Ella town. Expected re-opening next Monday.',
    bypassAdvice: 'Contact manager for partner property voucher.',
    utilities: {
      generatorStatus: 'Standby Only',
      waterStatus: 'Limited Supply',
      connectivityStatus: 'Staff Phone Active'
    },
    contactNumber: '077 889 0011',
    verifiedBy: 'NBRO Geotechnical Unit',
    verifiedAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 400 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 240 * 60 * 1000).toISOString()
  }
];
